from . import test_text_renderer
from . import test_canonical_model
from . import test_dsl_parser
from . import test_portal_generate
from . import test_portal_template_reference
from . import test_starter_template
from . import test_template_reference
from . import test_template_linter
from . import test_template_model
